mssn_app/main.py
from flask import Blueprint, render_template, request, flash, redirect, current_app, send_from_directory, url_for
from .models import User, Subscription, db, Executive, AcademicYear, Article, Document, DocumentCategory, Event, ArticleCategory, AboutPage, AboutSection
from sqlalchemy.exc import IntegrityError
from flask_mail import Message, Mail
import os
from flask_ckeditor import upload_success, upload_fail
from markupsafe import Markup
from flask_paginate import Pagination, get_page_parameter
from decouple import config
from flask_sitemapper import Sitemapper


bp = Blueprint('main', __name__)
sitemapper = Sitemapper()


def strip_html_tags(text):
    """Remove HTML tags from the given text."""
    return Markup(text).striptags()

@sitemapper.include()
@bp.route('/')
def index():
    academic_year = AcademicYear.query.all()
    events = Event.query.all()
    
    # Articles objects with pagination
    per_page = 6
    page = request.args.get(get_page_parameter(), type=int, default=1)
    articles = Article.query.order_by(
        Article.updated_at.desc()).paginate(page=page, per_page=per_page)
    total = len(Article.query.all())
    pagination = Pagination(page=page, per_page=per_page,
                            total=total, record_name='articles')
    try:
        about_section = AboutSection.query.first()
    except:
        about_section = None
    return render_template('main/index.html', academic_year=academic_year, events=events, articles=articles, pagination=pagination, about_section=about_section)


@bp.route('/subscribe', methods=['GET', 'POST'])
def subscription():
    if request.method == 'POST':
        error = None
        referrer = request.referrer
        email = request.form['email']
        full_name = request.form['full_name']
        mail = current_app.extensions['mail']

        if not email and full_name:
            error = "All fields are required"
        if error is None:
            try:
                new_subscription = Subscription(
                    full_name=full_name, email=email)
                db.session.add(new_subscription)
                db.session.commit()
                html_content = render_template(
                    'main/subscription_email.html', name=new_subscription.full_name)
                message = Message(subject='Welcome to MSSN OAUSTECH', sender=config('MAIL_USERNAME'),
                                  recipients=[new_subscription.email], html=html_content)
                mail.send(message)
                flash('You have subscribed successfully!', "success")
                return redirect(referrer)
            except IntegrityError:
                error = "Email is already registered"

        flash(error, "danger")
        return redirect(referrer)

@sitemapper.include()
@bp.route('/executive_list/')
def executive_year_list():
    academic_year = AcademicYear.query.all()
    return render_template('main/executive_year_list.html', academic_year=academic_year)


@bp.route('/executive_list/<path:year>')
def executive_detail_list(year):
    referrer = request.referrer
    filter_year = AcademicYear.query.filter_by(year=year).first()
    try:
        executive_list = Executive.query.filter_by(
            academic_year_id=filter_year.id)
    except:
        return redirect(referrer)
    return render_template('main/executive_detail_list.html', executive_list=executive_list, year=year)

@sitemapper.include()
@bp.route('/articles/')
def article_list():
    category_id = request.args.get('category')
    search_query = request.args.get('q')
    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = 6
    categories = ArticleCategory.query.all()
    if search_query:
        article_list = Article.query.filter(Article.title.ilike(f"%{search_query}%")).order_by(
            Article.updated_at.desc()).paginate(page=page, per_page=per_page)
    else:
        if category_id:
            article_list = Article.query.filter_by(category_id=category_id).order_by(
                Article.updated_at.desc()).paginate(page=page, per_page=per_page)
        else:
            article_list = Article.query.order_by(
                Article.updated_at.desc()).paginate(page=page, per_page=per_page)

    # If no results found for the search query
    if article_list.total == 0:
        message = f"No results found for '{search_query}'."
        return render_template('main/no_results.html', message=message)

    total = article_list.total

    pagination = Pagination(page=page, per_page=per_page,
                            total=total, record_name='articles')
    return render_template('main/article_list.html', article_list=article_list, pagination=pagination, categories=categories)


@bp.route('/articles/<int:id>/')
def article_detail(id):
    article = Article.query.get(id)
    latest_posts = Article.query.filter(Article.id != id).order_by(
        Article.updated_at.desc()).limit(4).all()
    return render_template('main/article_detail.html', article=article, latest_posts=latest_posts)

@sitemapper.include()
@bp.route('/mssn-oaustech-library/')
def mssn_oaustech_library():
    document_category = DocumentCategory.query.all()
    for category in document_category:
        category.documents = Document.query.filter_by(
            category_id=category.id).all()
    return render_template('main/library.html', document_category=document_category)


@bp.route('/documents/<int:document_id>/download')
def download_document(document_id):
    document = Document.query.get(document_id)
    upload_folder = current_app.config['UPLOAD_FOLDER']
    return send_from_directory(upload_folder, document.document_file, as_attachment=True)


@bp.route('/upload', methods=['GET', 'POST'])
def upload():
    upload_folder = current_app.config['UPLOAD_FOLDER']
    f = request.files.get('upload')
    if f:
        extension = f.filename.split('.')[-1].lower()
        if extension not in ['jpg', 'gif', 'png', 'jpeg']:
            return upload_fail(message='Image only!')
        f.save(os.path.join(upload_folder, f.filename))
        url = url_for('main.uploaded_files', filename=f.filename)
        return upload_success(url, filename=f.filename)
    return upload_fail(message='No file uploaded')


# Route for serving uploaded files
@bp.route('/files/<path:filename>')
def uploaded_files(filename):
    # path =config('UPLOAD_FOLDER')
    path = current_app.config['UPLOAD_FOLDER']
    file_path = os.path.join(path, filename)
    return send_from_directory(os.path.dirname(file_path), os.path.basename(file_path))

@sitemapper.include()
@bp.route('/contact-us/')
def contact_us():
    return render_template('main/contact.html')

@sitemapper.include()
@bp.route('/donate/')
def donate():
    return render_template('main/donate.html')

@sitemapper.include()
@bp.route('/about/')
def about():
    try:
        about_page = AboutPage.query.first()
    except:
        about_page = None
    return render_template('main/about.html', about_page=about_page)
    
@bp.route("/sitemap.xml")
def sitemap():
  return sitemapper.generate()

mssn_app/templates/article_list.html
{% extends "base.html" %}
{% block title %}
    Articles
{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{{url_for('static',filename='article_style.css')}}">
{% endblock style %}
    
{% block content %}
    <div id="main-content" class="blog-page">
        <div class="container">
            <h1>ARTICLES</h1>
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 left-box">
                    {% for article in article_list %}
                        <div class="card single_post">
                            <div class="body">
                                <div class="img-post">
                                    
                                    {% if article.cover_photo %}
                                    <img class="d-block img-fluid"
                                    src="{{url_for('static',filename='uploads/' + article.cover_photo)}}"
                                    alt="{{article.title}}">
                                    {% else %}
                                    <img class="d-block img-fluid"
                                         src="https://www.bootdey.com/image/800x280/FFB6C1/000000"
                                         alt="First slide">
                                    {% endif %}
                                        
                                </div>
                                <h3>
                                    <a href="{{url_for('main.article_detail', id=article.id)}}">{{article.title}}</a>
                                </h3>
                                <p>
                                    {{ article.body |strip_html_tags|truncate(200) }}                             </p>
                            </div>
                            <div class="footer">
                                <div class="actions">
                                    <a href="{{url_for('main.article_detail',id=article.id)}}" class="btn btn-outline-secondary">Continue Reading</a>
                                </div>
                                <!-- <ul class="stats">
                                    <li>
                                        <a href="javascript:void(0);">General</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);" class="fa fa-heart">28</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);" class="fa fa-comment">128</a>
                                    </li>
                                </ul> -->
                            </div>
                        </div>
                    {% endfor %}
                    <div class="mt-3 d-flex justify-content-center">{{ pagination.links }}</div>
                </div>
                <div class="col-lg-4 col-md-12 right-box">
                    <div class="card">
                        <div class="body search">
                            <form action=""><div class="input-group m-b-0">
                                <span class="input-group-text" id="addon-wrapping"><i class="fa fa-search"></i></span>
                            <input type="text" class="form-control" aria-describedby="basic-addon1" placeholder="Search..." name="q">
                        </div></form>
                        </div>
                    </div>
                    <div class="card">
                        <div class="header">
                            <h2>Categories Filter</h2>
                        </div>
                        <div class="body widget">
                            <ul class="list-unstyled categories-clouds m-b-0">
                                <li><a href="{{ url_for('main.article_list') }}">All</a></li>
                                {% for category in categories %}
                                    <li><a href="{{ url_for('main.article_list', category=category.id) }}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <!-- <div class="card">
                        <div class="header">
                            <h2>Popular Posts</h2>
                        </div>
                        <div class="body widget popular-post">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="single_post">
                                        <p class="m-b-0">Apple Introduces Search Ads Basic</p>
                                        <span>jun 22, 2018</span>
                                        <div class="img-post">
                                            <img src="https://www.bootdey.com/image/280x280/FFB6C1/000000"
                                                 alt="Awesome Image">
                                        </div>
                                    </div>
                                    <div class="single_post">
                                        <p class="m-b-0">new rules, more cars, more races</p>
                                        <span>jun 8, 2018</span>
                                        <div class="img-post">
                                            <img src="https://www.bootdey.com/image/280x280/FFB6C1/000000"
                                                 alt="Awesome Image">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="header">
                            <h2>Instagram Post</h2>
                        </div>
                        <div class="body widget">
                            <ul class="list-unstyled instagram-plugin m-b-0">
                                <li>
                                    <a href="javascript:void(0);">
                                        <img src="https://www.bootdey.com/image/80x80/FFB6C1/000000"
                                             alt="image description">
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <img src="https://www.bootdey.com/image/80x80/FFB6C1/000000"
                                             alt="image description">
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <img src="https://www.bootdey.com/image/80x80/FFB6C1/000000"
                                             alt="image description">
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <img src="https://www.bootdey.com/image/80x80/FFB6C1/000000"
                                             alt="image description">
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <img src="https://www.bootdey.com/image/80x80/FFB6C1/000000"
                                             alt="image description">
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <img src="https://www.bootdey.com/image/80x80/FFB6C1/000000"
                                             alt="image description">
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <img src="https://www.bootdey.com/image/80x80/FFB6C1/000000"
                                             alt="image description">
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <img src="https://www.bootdey.com/image/80x80/FFB6C1/000000"
                                             alt="image description">
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <img src="https://www.bootdey.com/image/80x80/FFB6C1/000000"
                                             alt="image description">
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block subscription %}
    {% include "subscription_form.html" %}
{% endblock subscription %}
    

mssn_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {# {{ ckeditor.load() }} #}
        {% include "head.html" %}
        <title>
            {% block title %}
            {% endblock title %}
            - MSSN OAUSTECH
        </title>
        {% block style %}
        {% endblock style %}
        {% block meta %}
        {% endblock meta %}
    </head>
    <body>
        {% include "navbar.html" %}
        {% with msg = get_flashed_messages(with_categories=True) %}
            {% if msg %}
                {% for category,message in msg %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show text-center"
                         role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button"
                                class="btn-close"
                                data-bs-dismiss="alert"
                                aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock content %}
        {% include "footer.html" %}
        {% block subscription %}
        {% endblock subscription %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                crossorigin="anonymous"></script>
        {# {{ ckeditor.config() }} #}
    </body>
</html>

mssn_app/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}
    Admin Dashboard
{% endblock title %}
    
    {% block content %}
        <h3>Welcome {{user.username}}</h3>
        <h4>Your email is {{user.email}}</h4>
        <div>
            <h3>Acctive subscriptions</h3>
            
            {% for subscription in subscriptions %}
                {{subscription}}
            {% endfor %}

            <h3>Academic years</h3>
            
            {% for year in academic_year %}
                {{year}}
            {% endfor %}

            <h3>Executive</h3>
            
            {% for executive in executive %}
                {{executive.name}} --> {{executive.academic_year}}
            {% endfor %}
                
                

            <h3>Year form</h3>
            <form action="{{url_for('main.add_academic_year')}}" method="post">
                <input type="text" name="year" id="">
                <button type="submit">Add Year</button>
            </form>
            <h4>Executive Form</h4>
            <form action="{{url_for('main.add_executive')}}" method="post">
                <input type="text" name="name" id="" placeholder="Executive full name">
                <input type="text" name="position" id="" placeholder="post held">
                <select name="academic_year_id" id="">
                    
                    {% for year in academic_year %}
                        <option value="{{year.id}}">{{year.year}}</option>
                    {% endfor %}
                        
                </select>
                <button type="submit">submit</button>
            </form>


            <h3>Mail form</h3>
            <form action="{{url_for('main.newsletter')}}" method="post">
                <input type="text" name="subject" id="" placeholder="Email Subject">
                <input type="text" name="body" id="" placeholder="Email Body">
                <button type="submit">Send Mail</button>
            </form>

            <h3>Add Article</h3>
            <form action="{{url_for('main.article_create')}}" method="post" enctype="multipart/form-data">
                <select name="category_id" id="">
                    
                    {% for category in article_category  %}
                        <option value="{{category.id}}">{{category.name}}</option>
                    {% endfor %}
                        
                </select>
                <input type="text" name="title" id="">
                <input type="file" name="cover_photo" accept="image/*" required>
                {{ ckeditor.create() }}
                <button type="submit">Add Article</button>
            </form>
            <h3>Add document category</h3>
            <form action="{{url_for('main.add_document_category')}}" method="post">
                <input type="text" name="name" id="">
                <button type="submit">Add Category</button>
            </form>
                

            <h3>Add document</h3>
            <form action="{{url_for('main.add_document')}}" method="post" enctype="multipart/form-data">
                <input type="text" name="title" id="">
                <input type="file" name="document_file" id="">
                <select name="category_id" id="">
                    
                    {% for category in document_category  %}
                        <option value="{{category.id}}">{{category.name}}</option>
                    {% endfor %}
                        
                </select>
                <button type="submit">Add document</button>
            </form>
            
            {% for document in document %}
                <!-- <img src="{{ url_for('static', filename=document.document_file) }}" alt="hello"> -->
                <!-- <img src="{{ url_for('static', filename='uploads/' + document.document_file) }}" alt="f"> -->
                <a href="{{url_for('static',filename=document.document_file)}}" target="_blank" download>{{document.title}}</a>

                
                
            {% endfor %}    
            <div>
                <form action="{{url_for('main.add_event')}}" method="post" enctype="multipart/form-data">
                    <input type="file" name="image" accept="image/*" required>
                    <button type="submit">Add Event</button>
                </form>
            </div>  
            <div>
                <form action="{{url_for('main.add_article_category')}}" method="post">
                    <input type="text" name="category" id="">
                    <button type="submit">Add article category</button>
                </form>
            </div>          
        </div>
    
    {% endblock content %}
        

mssn_app/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock title %}
    

{% block content %}
    <form action="" method="post">
        <label for="username">Username</label>
        <input type="text" name="username">
        <label for="password">Password</label>
        <input type="password" name="password" id="">
        <button>Login</button>
    </form>
{% endblock content %}
    

mssn_app/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary px-lg-5 px-sm-3 sticky-top shadow py-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='img/mssn-logo.webp') }}"
                 alt="mssn-logo"
                 width="53"
                 height="50">
            <img src="{{ url_for('static', filename='img/oaustech-logo.webp') }}"
                 alt="oaustech-logo"
                 width="53"
                 height="50">
        </a>
        <button class="navbar-toggler"
                id="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <i class="fa-solid fa-bars-staggered" id="ham-icon"></i>
            <i class="fa-solid fa-x d-none" id="x-icon"></i>
            <!--<span class="navbar-toggler-icon"></span>-->
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
            <ul class="navbar-nav ms-auto nav-underline nav-fill">
                <li class="nav-item">
                    <a class="nav-link {{ 'active' if active_page=='home' else '' }} "
                       aria-current="page"
                       href='{{ url_for("main.index") }}'><i class="fa-solid fa-landmark-dome"></i> HOME</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                       href="#"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false"><i class="fa-solid fa-address-card"></i> ABOUT US</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="{{url_for('main.about')}}">About MSSN OAUSTECH</a>
                        </li>
                        <li>
                            <a class="dropdown-item"
                               href="{{ url_for("main.executive_year_list") }}">MSSN OAUSTECH EXCOS</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{{ url_for("main.contact_us") }}">Contact Us</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ 'active' if active_page=='article' else '' }}"
                       href="{{ url_for("main.article_list") }}"><i class="fa-regular fa-newspaper"></i> NEWS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ 'active' if active_page=='library' else '' }}"
                       href="{{ url_for("main.mssn_oaustech_library") }}"><i class="fa-solid fa-book"></i> MSSN E-LIBRARY</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                       href="#"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false"><i class="fa-solid fa-list-check"></i> PROGRAMMES</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="#">Jihad Week</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Islamic Lectures</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Sister's Circle</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Ushrah Class</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Islamic Lectures</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ 'active' if active_page=='donate' else '' }}"
                       href="{{ url_for("main.donate") }}"><i class="fa-solid fa-circle-dollar-to-slot"></i> DONATE</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="#"
                       data-bs-toggle="modal"
                       data-bs-target="#searchModal"><i class="fa fa-search"></i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="modal fade"
     id="searchModal"
     tabindex="-1"
     aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for("main.article_list") }}">
                    <div class="input-group m-b-0">
                        <span class="input-group-text" id="addon-wrapping"><i class="fa fa-search"></i></span>
                        <input type="text"
                               class="form-control"
                               aria-describedby="basic-addon1"
                               placeholder="Search..."
                               name="q">
                        <button class="btn btn-success" type="submit">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    // Wait for the DOM to be fully loaded before accessing elements
    document.addEventListener("DOMContentLoaded", function() {
        var navToggler = document.getElementById("navbar-toggler");
        var hamIcon = document.getElementById('ham-icon');
        var xIcon = document.getElementById('x-icon');
        
        // Use addEventListener for click event
        navToggler.addEventListener('click', function() {
            // Use classList.contains() to check if a class exists
            if (xIcon.classList.contains("d-none")) {
                hamIcon.classList.add("d-none");
                xIcon.classList.remove("d-none");
            } else {
                hamIcon.classList.remove("d-none");
                xIcon.classList.add("d-none");
            }
        });
    });
</script>

mssn_app/templates/subscription_form.html
<div class="sticky-bottom d-flex justify-content-center ps-3 py-2 subscribe-bg">
    <form action='{{ url_for("main.subscription") }}' method="post">
        
        <div class="row">
            <h5 class="subscribe-head">Subscribe to our Newsletter</h5>
            <div class="col-auto">
                <input type="text" class="form-control" name="full_name" placeholder="Full name (Surname first)">

            </div>
            <div class="col-auto">
                <input type="email" class="form-control" name="email" placeholder="Email">

            </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-light">Subscribe</button>
        </div>
        </div>
    </form>
</div>