mssn_app/main.py
from flask import Blueprint, render_template, request, flash, redirect, current_app, send_from_directory, url_for
from .models import User, Subscription, db, Executive, AcademicYear, Article, Document, DocumentCategory, Event, ArticleCategory, AboutPage, AboutSection
from sqlalchemy.exc import IntegrityError
from flask_mail import Message, Mail
import os
from flask_ckeditor import upload_success, upload_fail
from markupsafe import Markup
from flask_paginate import Pagination, get_page_parameter
from decouple import config
from flask_sitemapper import Sitemapper


bp = Blueprint('main', __name__)
sitemapper = Sitemapper()


def strip_html_tags(text):
    """Remove HTML tags from the given text."""
    return Markup(text).striptags()

@sitemapper.include()
@bp.route('/')
def index():
    academic_year = AcademicYear.query.all()
    events = Event.query.all()
    
    # Articles objects with pagination
    per_page = 6
    page = request.args.get(get_page_parameter(), type=int, default=1)
    articles = Article.query.order_by(
        Article.updated_at.desc()).paginate(page=page, per_page=per_page)
    total = len(Article.query.all())
    pagination = Pagination(page=page, per_page=per_page,
                            total=total, record_name='articles')
    try:
        about_section = AboutSection.query.first()
    except:
        about_section = None
    return render_template('main/index.html', academic_year=academic_year, events=events, articles=articles, pagination=pagination, about_section=about_section)


@bp.route('/subscribe', methods=['GET', 'POST'])
def subscription():
    if request.method == 'POST':
        error = None
        referrer = request.referrer
        email = request.form['email']
        full_name = request.form['full_name']
        mail = current_app.extensions['mail']

        if not email and full_name:
            error = "All fields are required"
        if error is None:
            try:
                new_subscription = Subscription(
                    full_name=full_name, email=email)
                db.session.add(new_subscription)
                db.session.commit()
                html_content = render_template(
                    'main/subscription_email.html', name=new_subscription.full_name)
                message = Message(subject='Welcome to MSSN OAUSTECH', sender=config('MAIL_USERNAME'),
                                  recipients=[new_subscription.email], html=html_content)
                mail.send(message)
                flash('You have subscribed successfully!', "success")
                return redirect(referrer)
            except IntegrityError:
                error = "Email is already registered"

        flash(error, "danger")
        return redirect(referrer)

@sitemapper.include()
@bp.route('/executive_list/')
def executive_year_list():
    academic_year = AcademicYear.query.all()
    return render_template('main/executive_year_list.html', academic_year=academic_year)


@bp.route('/executive_list/<path:year>')
def executive_detail_list(year):
    referrer = request.referrer
    filter_year = AcademicYear.query.filter_by(year=year).first()
    try:
        executive_list = Executive.query.filter_by(
            academic_year_id=filter_year.id)
    except:
        return redirect(referrer)
    return render_template('main/executive_detail_list.html', executive_list=executive_list, year=year)

@sitemapper.include()
@bp.route('/articles/')
def article_list():
    category_id = request.args.get('category')
    search_query = request.args.get('q')
    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = 6
    categories = ArticleCategory.query.all()
    if search_query:
        article_list = Article.query.filter(Article.title.ilike(f"%{search_query}%")).order_by(
            Article.updated_at.desc()).paginate(page=page, per_page=per_page)
    else:
        if category_id:
            article_list = Article.query.filter_by(category_id=category_id).order_by(
                Article.updated_at.desc()).paginate(page=page, per_page=per_page)
        else:
            article_list = Article.query.order_by(
                Article.updated_at.desc()).paginate(page=page, per_page=per_page)

    # If no results found for the search query
    if article_list.total == 0:
        message = f"No results found for '{search_query}'."
        return render_template('main/no_results.html', message=message)

    total = article_list.total

    pagination = Pagination(page=page, per_page=per_page,
                            total=total, record_name='articles')
    return render_template('main/article_list.html', article_list=article_list, pagination=pagination, categories=categories)


@bp.route('/articles/<int:id>/')
def article_detail(id):
    article = Article.query.get(id)
    latest_posts = Article.query.filter(Article.id != id).order_by(
        Article.updated_at.desc()).limit(4).all()
    return render_template('main/article_detail.html', article=article, latest_posts=latest_posts)

@sitemapper.include()
@bp.route('/mssn-oaustech-library/')
def mssn_oaustech_library():
    document_category = DocumentCategory.query.all()
    for category in document_category:
        category.documents = Document.query.filter_by(
            category_id=category.id).all()
    return render_template('main/library.html', document_category=document_category)


@bp.route('/documents/<int:document_id>/download')
def download_document(document_id):
    document = Document.query.get(document_id)
    upload_folder = current_app.config['UPLOAD_FOLDER']
    return send_from_directory(upload_folder, document.document_file, as_attachment=True)


@bp.route('/upload', methods=['GET', 'POST'])
def upload():
    upload_folder = current_app.config['UPLOAD_FOLDER']
    f = request.files.get('upload')
    if f:
        extension = f.filename.split('.')[-1].lower()
        if extension not in ['jpg', 'gif', 'png', 'jpeg']:
            return upload_fail(message='Image only!')
        f.save(os.path.join(upload_folder, f.filename))
        url = url_for('main.uploaded_files', filename=f.filename)
        return upload_success(url, filename=f.filename)
    return upload_fail(message='No file uploaded')


# Route for serving uploaded files
@bp.route('/files/<path:filename>')
def uploaded_files(filename):
    # path =config('UPLOAD_FOLDER')
    path = current_app.config['UPLOAD_FOLDER']
    file_path = os.path.join(path, filename)
    return send_from_directory(os.path.dirname(file_path), os.path.basename(file_path))

@sitemapper.include()
@bp.route('/contact-us/')
def contact_us():
    return render_template('main/contact.html')

@sitemapper.include()
@bp.route('/donate/')
def donate():
    return render_template('main/donate.html')

@sitemapper.include()
@bp.route('/about/')
def about():
    try:
        about_page = AboutPage.query.first()
    except:
        about_page = None
    return render_template('main/about.html', about_page=about_page)
    
@bp.route("/sitemap.xml")
def sitemap():
  return sitemapper.generate()

mssn_app/templates/main/article_detail.html
{% extends "base.html" %}
{% block title %}
    {{ article.title }}
{% endblock title %}
{% block style %}
    <link rel="stylesheet"
          href="{{ url_for('static',filename='style/article-detail-style.css') }}">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
{% endblock style %}
{% block content %}
    <div class="blog-single gray-bg">
        <div class="container">
            <div class="row align-items-start">
                <div class="col-lg-8 m-15px-tb">
                    <div class="article">
                        <div class="article-img">
                            {% if article.cover_photo %}
                                <img src="{{ url_for('main.uploaded_files',filename= article.cover_photo) }}"
                                     title=""
                                     alt=""
                                     width=""
                                     height="">
                            {% else %}
                                <img src="{{ url_for('static',filename='img/article_cover.webp') }}"
                                     title=""
                                     alt=""
                                     width=""
                                     height="">
                            {% endif %}
                        </div>
                        <div class="article-title">
                            <h6>
                                <a href="#">{{ article.article_category }}</a>
                            </h6>
                            <h2>{{ article.title }}</h2>
                        </div>
                        <div class="article-content">{{ article.body | safe }}</div>
                    </div>
                </div>
                <div class="col-lg-4 m-15px-tb blog-aside">
                    <!-- Latest Post -->
                    <div class="widget widget-latest-post">
                        <div class="widget-title">
                            <h3>Latest Post</h3>
                        </div>
                        <div class="widget-body">
                            {% for post in latest_posts %}
                                <div class="latest-post-aside media">
                                    <div class="lpa-left media-body">
                                        <div class="lpa-title">
                                            <h5>
                                                <a href="{{ url_for('main.article_detail',id=post.id) }}">{{ post.title }}</a>
                                            </h5>
                                        </div>
                                        <div class="lpa-meta">
                                            <!--<a class="name" href="#">
                                            Rachel Roth
                                        </a>-->
                                            <a class="date" href="{{ url_for('main.article_detail',id=post.id) }}">{{ article.updated_at.strftime("%B %d, %Y") }}</a>
                                        </div>
                                    </div>
                                    <div class="lpa-right">
                                        <a href="{{ url_for('main.article_detail',id=post.id) }}">
                                            {% if post.cover_photo %}
                                                <img src="{{ url_for('static',filename='uploads/' + post.cover_photo) }}"
                                                     title=""
                                                     alt=""
                                                     width=""
                                                     height="">
                                            {% else %}
                                                <img src="{{ url_for('static',filename='img/article_cover.webp') }}"
                                                     title=""
                                                     alt=""
                                                     width=""
                                                     height="">
                                            {% endif %}
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- End Latest Post -->
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

mssn_app/templates/main/article_list.html
{% extends "base.html" %}
{% set active_page = "article" %}
{% block title %}
    Articles
{% endblock title %}
{% block meta %}
    <meta name="description"
          content="Explore insightful articles on Islam, campus life, and community events at OAUSTECH. Stay informed and engaged with our latest updates.">
    <meta name="keywords"
          content="mssn,oaustech,mssnoaustech,mssn oaustech,islam,islamic,organization,campus,mssn branch, oaustech muslim,okitipupa,religious,muslim student,muslim students, olusegun agagu univerisity,mss, mss ondo,mss oaustech,osustect,mssn osustech,mss osustech,OAUSTECH articles, campus news, Islamic articles, Muslim community, student life, educational resources">
{% endblock meta %}
{% block style %}
    <link rel="preload" 
          href="{{ url_for('static',filename='style/article_style.css') }}" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="{{ url_for('static',filename='style/article_style.css') }}"></noscript>
{% endblock style %}
{% block content %}
    <div id="main-content" class="blog-page mt-5">
        <div class="container">
            <h1 class="ms-5">ARTICLES</h1>
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 left-box">
                    {% for article in article_list %}
                        <div class="card single_post">
                            <div class="body">
                                <div class="img-post">
                                    {% if article.cover_photo %}
                                        <img class="d-block img-fluid"
                                             src="{{ url_for('main.uploaded_files',filename=article.cover_photo) }}"
                                             alt="{{ article.title }}"
                                             height=""
                                             width="">
                                    {% else %}
                                        <!--<img class="d-block img-fluid"
     src="https://www.bootdey.com/image/800x280/FFB6C1/000000"
     alt="First slide">-->
                                        <img class="d-block img-fluid"
                                             src="{{ url_for('static',filename='img/article_cover.webp') }}"
                                             alt="First slide"
                                             height=""
                                             width="">
                                    {% endif %}
                                </div>
                                <h3>
                                    <a href="{{ url_for('main.article_detail', id=article.id) }}">{{ article.title }}</a>
                                </h3>
                                <p>{{ article.body |strip_html_tags|truncate(200) }}</p>
                            </div>
                            <div class="footer">
                                <div class="actions">
                                    <a href="{{ url_for('main.article_detail',id=article.id) }}"
                                       class="btn btn-outline-secondary">Continue Reading</a>
                                </div>
                                
                            </div>
                        </div>
                    {% endfor %}
                    <div class="mt-3 d-flex justify-content-center">{{ pagination.links }}</div>
                </div>
                <div class="col-lg-4 col-md-12 right-box">
                    <div class="card">
                        <div class="body search">
                            <form action="">
                                <div class="input-group m-b-0">
                                    <span class="input-group-text" id="addon-wrapping"><i class="fa fa-search"></i></span>
                                    <input type="text"
                                           class="form-control"
                                           aria-describedby="basic-addon1"
                                           placeholder="Search..."
                                           name="q">
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card">
                        <div class="header">
                            <h2>Categories Filter</h2>
                        </div>
                        <div class="body widget">
                            <ul class="list-unstyled  categories-clouds m-b-0">
                                <li>
                                    <a href="{{ url_for("main.article_list") }}" class="text-success">All</a>
                                </li>
                                {% for category in categories %}
                                    <li>
                                        <a href="{{ url_for('main.article_list', category=category.id) }}"
                                           class="text-success">{{ category.name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block subscription %}
    {% include "main/subscription_form.html" %}
{% endblock subscription %}

mssn_app/templates/main/donate.html
{% extends "base.html" %}
{% set active_page = "donate" %}
{% block title %}
    Donate
{% endblock title %}
{% block meta %}
    <meta name="description"
          content="Support the mission of MSSN OAUSTECH with your generous donations. Contribute to our programs and initiatives aimed at fostering unity, promoting Islamic values, and empowering students on campus." />
    <meta name="keywords"
          content="MSSN OAUSTECH donations, support MSSN, charitable giving, Islamic charity, campus initiatives, student empowerment,mssn,oaustech,mssnoaustech,mssn oaustech,islam,islamic,organization,campus,mssn branch, oaustech muslim,okitipupa,religious,muslim student,muslim students, olusegun agagu univerisity,mss, mss ondo,mss oaustech,osustect,mssn osustech,mss osustech" />
{% endblock meta %}
{% block content %}
    <section class="mt-5 text-muted">
        <div class="container w-50 mx-auto">
            <div>
                <h1 class="text-center display-5 fw-bold text-success">DONATE TO MSSN OAUSTECH</h1>
                <hr />
                <figure class="p-4">
                    <blockquote class="blockquote">
                        <p class="pb-2">
                            <em>
                                <i class="fas fa-quote-left fa-xs"></i>
                                Whoever does righteousness, whether male or female, while he is a believer - We will surely cause him to live a good life, and We will surely give them their reward [in the Hereafter] according to the best of what they used to do. (Quran 16:97)
                                <i class="fas fa-quote-right fa-xs"></i>
                            </em>
                        </p>
                    </blockquote>
                </figure>
            </div>
            <div class="mb-5">
                <h3>MSSN OAUSTECH BANK ACCOUNT DETAILS</h3>
                <hr />
                <ul class="list-unstyled">
                    <li class="fs-5">
                        <strong>Account Name:</strong> Muslim Students' Society of Nigeria, OAUSTECH
                    </li>
                    <li class="fs-5">
                        <strong>Bank Name</strong> Polaris Bank
                    </li>
                    <li class="fs-5">
                        <strong>Account Number</strong> 1140154382
                    </li>
                </ul>
            </div>
            <div class="mb-5">
                <h3>IMPACT OF YOUR DONATION</h3>
                <hr />
                <p class="fs-5 fw-light">
                    Your generous contribution to MSSN OAUSTECH will support various essential initiatives, including website maintenance, transportation logistics such as our bus service, and the welfare of Muslim students at our university. Your donation enables us to continue serving the community and providing essential services to those in need.
                </p>
            </div>
            <div>
                <h3 class="text-upper">REWARDS OF CHARITY</h3>
                <hr />
                <figure class="p-4 pb-0">
                    <blockquote class="blockquote">
                        <p>
                            <em>
                                <i class="fas fa-quote-left fa-xs"></i>
                                Those who in charity spend of their goods by night and by day, in secret and in public, have their reward with their Lord: on them shall be no fear, nor shall they grieve.(2:274)
                                <i class="fas fa-quote-right fa-xs"></i>
                            </em>
                        </p>
                    </blockquote>
                </figure>
                <span class="fs-5 fw-light">May Allah accept your donation and reward you manifold in this life and the Hereafter.</span>
            </div>
            <p class="my-3 fs-5">
                For verification or further information, please feel free to contact us <a class="text-success fw-bold" href="{{ url_for("main.contact_us") }}">HERE</a>
            </p>
        </div>
    </section>
{% endblock content %}

mssn_app/templates/main/executive_year_list.html
{% extends "base.html" %}
{% block title %}
    MSSN Executives
{% endblock title %}
{% block meta %}
    <meta name="description"
          content="Meet the dedicated leaders of MSSN OAUSTECH. Learn about our executive team members who work tirelessly to serve the Muslim student community and promote Islamic values on campus.">
    <meta name="keywords"
          content="MSSN OAUSTECH executives, student leadership, Muslim leaders, campus organization, leadership team, executive committee,mssn,oaustech,mssnoaustech,mssn oaustech,islam,islamic,organization,campus,mssn branch, oaustech muslim,okitipupa,religious,muslim student,muslim students, olusegun agagu univerisity,mss, mss ondo,mss oaustech,osustect,mssn osustech,mss osustech">
{% endblock meta %}
{% block content %}
    <div class="container my-5">
        <h2 class="mb-4">MSSN OAUSTECH Executives</h2>
        <div class="row">
            <div class="col-md-6">
                <ul class="list-group">
                    {% for year in academic_year %}
                        <li class="list-group-item">
                            <a class="exco-year-link"
                               href="{{ url_for('main.executive_detail_list',year=year) }}">{{ year }} MSSN OAUSTECH Executives</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

mssn_app/templates/main/index.html
{% extends "base.html" %}
{% set active_page = "home" %}
{% block title %}
    Homepage
{% endblock title %}
{% block meta %}
    <meta name="description"
          content="Official website of the Muslim Students' Society of Nigeria at, Olusegun Agagu University Of Scienc and Technology (OAUSTECH),  Branch.">
    <meta name="keywords"
          content="mssn,oaustech,mssnoaustech,mssn oaustech,islam,islamic,organization,campus,mssn branch, oaustech muslim,okitipupa,religious,muslim student,muslim students, olusegun agagu univerisity,mss, mss ondo,mss oaustech,osustect,mssn osustech,mss osustech">
{% endblock meta %}
{% block content %}
    <main>
        <section class="welcome-section">
            <div class="text-container">
                <div class="text-center  pt-5">
                    <h1 class="display-4 header-text">
                        MSSN OAUSTECH
                        <br>
                        Official Website
                    </h1>
                    <p>As salaam Alaykum Warahmatulah Wabarakatuh.</p>
                    <div class="welcome-text">
                        <p>You're welcome to the official website of the Muslim Students' Society of Nigeria at, OAUSTECH Branch.</p>
                        <p>
                            Join us on this journey of learning and friendship.
                            <br>
                            Explore our events, resources, and opportunities to grow academically and spiritually.
                        </p>
                        <p>Barakallahu feekum</p>
                    </div>
                </div>
            </div>
        </section>
        <section class=" about-section text-center shadow-sm m-md-5 ">
            <h1 class="display-4">About</h1>
            <hr>
            
            {% if about_section %}
            {{ about_section.content }}
            {% endif %}
                
        </section>
        <section class="events-section text-center shadow-sm m-md-5">
            <div class="container">
                <h1 class="display-4">Our Upcoming and Past Events</h1>
                <hr>
                <div class="row justify-content-center py-4">
                    <div>
                        <div id="carouselExampleRide"
                             class="carousel slide carousel-fade carousel-dark"
                             data-bs-ride="carousel">
                            <div class="carousel-indicators">
                                {% for item in events %}
                                    <button data-bs-target="#carouselExampleRide"
                                            data-bs-slide-to="{{ loop.index0 }}"
                                            {% if loop.first %}class="active"{% endif %}></button>
                                {% endfor %}
                            </div>
                            <div class="carousel-inner">
                                {% for item in events %}
                                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                                        <img src="{{ url_for('main.uploaded_files', filename=item.image) }}"
                                             class="d-block w-100"
                                             alt="Event Image"
                                             height=""
                                             width="">
                                    </div>
                                {% endfor %}
                            </div>
                            <button class="carousel-control-prev"
                                    type="button"
                                    data-bs-target="#carouselExampleRide"
                                    data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next"
                                    type="button"
                                    data-bs-target="#carouselExampleRide"
                                    data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class=" article-section container shadow-sm my-5 p-4">
            <div class="text-center py-4">
                <h1 class="display-4">Articles</h1>
                <hr>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="row">
                        {% for article in articles %}
                            <div class="col-md-6 col-xl-4 mt-4">
                                <article class="post">
                                    <div class="article-v2">
                                        <figure class="article-thumb">
                                            <a href="{{ url_for('main.article_detail',id=article.id) }}">
                                                {% if article.cover_photo %}
                                                    <img src="{{ url_for('main.uploaded_files', filename=article.cover_photo) }}"
                                                         alt="blog image"
                                                         class="article-img"
                                                         height=""
                                                         width="" />
                                                {% else %}
                                                    <img src="{{ url_for('static',filename='img/article_cover.webp') }}"
                                                         alt=""
                                                         class="article-img"
                                                         height=""
                                                         width="">
                                                {% endif %}
                                            </a>
                                        </figure>
                                        <div class="article-content-main">
                                            <div class="article-header">
                                                <h2 class="entry-title text-capitalize ">
                                                    <a href="#"
                                                       class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover text-dark">{{ article.title }}</a>
                                                </h2>
                                                <div class="entry-meta">
                                                    <div class="entry-date">{{ article.updated_at.strftime("%B %d, %Y") }}</div>
                                                    {#<div class="entry-cat">
                                                        <a href="#">Halie Rose</a>
                                                    </div>#}
                                                </div>
                                            </div>
                                            <div class="article-content">
                                                <p>{{ article.body |strip_html_tags|truncate(50) }}</p>
                                            </div>
                                            <div class="article-footer">
                                                <div class="row">
                                                    <div class="col-6 text-left footer-link">
                                                        <a href="{{ url_for('main.article_detail',id=article.id) }}"
                                                           class="more-link">Read More</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="mt-3 d-flex justify-content-center">{{ pagination.links }}</div>
        </section>
    </main>
{% endblock content %}
{% block subscription %}
    {% include "main/subscription_form.html" %}
{% endblock subscription %}